name: Build Kivy APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        # Cython sorunu için ekstra komut ekliyoruz
        command: pip3 install --user --upgrade Cython==0.29.36; buildozer -v android debug
        buildozer_version: stable
